routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/post/{slug}', 'HomeController@post_view')->name('post-view');
Route::get('/category/{id}', 'HomeController@category_view')->name('category-view');
Route::get('/admin', 'DashboardController@dashboard')->name('home');
Route::post('delete-record',array('as' => "delete-record",'uses'=> "DashboardController@delete_record"));
Route::post('restore-record',array('as' => "restore-record",'uses'=> "DashboardController@restore_record"));
Route::post('empty-records',array('as' => "empty-records",'uses'=> "DashboardController@empty_records"));
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::get('/categories/trash', 'CategoryController@trash');
    Route::resource('categories', 'CategoryController');
    Route::get('/posts/trash', 'PostController@trash');
    Route::resource('posts', 'PostController');
});

app/Post.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    use Sluggable;

    protected $fillable = ['title','slug','description','body','image','category_id','is_active','is_featured','meta_description','meta_keywords','published_at'];
    protected $dates = ['deleted_at', 'published_at'];

    public static $rules = [
        'title'       => 'required',
        'description'=>'required',
        'body'=>'required',
        'image' => 'required|image|dimensions:width=1920,height=1280',

    ];
    public static $update_rules = [
        'title' => 'required',
        'description'=>'required',
        'body'=>'required',
        'image' => 'nullable|image|dimensions:width=1920,height=1280',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function categories() {
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Post;
use App\PostCategory;
use Cviebrock\EloquentSluggable\Services\SlugService;
use Illuminate\Http\Request;

class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('posts.index')->with(['posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create', ['categories' => Category::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, Post::$rules);
        $image = $request->image->store('images/posts');
        $data['is_active'] = $request->is_active ? 1 : 0;
        $data['is_featured'] = $request->is_featured ? 1 : 0;
        $data['body'] = $request->body;
        $data['description'] = $request->description;
        $data['meta_description'] = $request->meta_description;
        $data['meta_keywords'] = $request->meta_keywords;
        $data['slug'] = SlugService::createSlug(Post::class, 'slug', $request->title);
        $data['title'] = $request->title;
        $data['post_id'] = $request->post_id;
        $data['image'] = $image;
        $categories = $request->categories;
        if($post = Post::create($data)) {
            $post->categories()->sync($categories);
        }
        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        return view('posts.edit')->with(['post' => $post, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request, Post::$update_rules);
        if ($request->hasFile('image')) {
            $image = $request->image->store('images/posts');
            $data['image'] = $image;
        } else {
            $data['image'] = $post->image;
        }
        $data['is_active'] = $request->is_active ? 1 : $post->is_active;
        $data['is_featured'] = $request->is_featured ? 1 : $post->is_featured;
        $data['body'] = $request->body ?? $post->body;
        $data['description'] = $request->description ?? $post->description;
        $data['meta_description'] = $request->meta_description ?? $post->meta_description;
        $data['meta_keywords'] = $request->meta_keywords ?? $post->meta_keywords;
        if ($request->title != $post->title) {
            $post->slug = null;
            $data['slug'] = SlugService::createSlug(Post::class, 'slug', $request->title);
        } else {
            $data['slug'] = $post->slug;
        }
        $data['title'] = $request->title ?? $post->title;

        if($post->update($data)) {
            $post->categories()->sync($request->categories);
        }
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return void
     */
    public function destroy(Post $post)
    {
        //
    }

    public function trash() {
        //
        $posts = Post::onlyTrashed()->get();
        return view('posts.trash', ['posts' => $posts]);
    }

    public function emptyTrash() {
        Post::onlyTrashed()->forceDelete();
        return redirect()->route('posts.index');
    }
}

resources/views/posts/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Create Posts')

@section('content_header')
    <h1>Create Posts <a href="{{ route('posts.create') }}" class="btn btn-primary pull-right">Create</a></h1>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form class="form-horizontal" action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="image">Post Banner</label>
                        <div class="input-group input-file" name="image">
                            <input type="text" class="form-control" placeholder='Choose a file...' />
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-choose" type="button">Choose</button>
                            </span>
                            <small id="titleHelp" class="form-text text-muted">{{ $errors->first('image') ?? 'This field required.' }}</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTitle">Post title</label>
                        <input type="text" name="title" class="form-control" id="exampleInputTitle" aria-describedby="titleHelp" placeholder="Enter title">
                        <small id="titleHelp" class="form-text text-muted">{{ $errors->first('title') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="categories[]">Category</label>
                        <select name="categories[]" multiple data-live-search="true" class="form-control selectpicker">
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->title }}</option>
                            @endforeach
                        </select>
                        <small id="category_idHelp" class="form-text text-muted">{{ $errors->first('category_id') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDescription">Post short description</label>
                        <textarea name="description" class="form-control" id="exampleInputDescription" aria-describedby="descriptionHelp"></textarea>
                        <small id="descriptionHelp" class="form-text text-muted">{{ $errors->first('description') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputBody">Post Content</label>
                        <textarea name="body" class="form-control" id="body" aria-describedby="bodyHelp"></textarea>
                        <small id="bodyHelp" class="form-text text-muted">{{ $errors->first('body') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDescription">Post meta description</label>
                        <textarea name="meta_description" class="form-control" id="exampleInputDescription" aria-describedby="descriptionHelp"></textarea>
                        <small id="descriptionHelp" class="form-text text-muted">{{ $errors->first('meta_description') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDescription">Post meta keywords</label>
                        <textarea name="meta_keywords" class="form-control" id="exampleInputDescription" aria-describedby="descriptionHelp"></textarea>
                        <small id="descriptionHelp" class="form-text text-muted">{{ $errors->first('meta_keywords') }}</small>
                    </div>
                    <div class="form-group">
                        <div class="form-check form-check-inline">
                            <label class="form-check-label col-md-2" for="is_active">
                                <input class="form-check-input" name="is_active" type="checkbox" id="is_active"> is active
                            </label>
                            <label class="form-check-label col-md-2" for="is_featured">
                                <input class="form-check-input" name="is_featured" type="checkbox" id="is_featured"> is Published
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success pull-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
@endsection

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'body' );
    </script>
    <script>
        $(function() {
            bs_input_file();
        });

        function bs_input_file() {
            $(".input-file").before(
                function() {
                    if ( ! $(this).prev().hasClass('input-ghost') ) {
                        var element = $("<input type='file' class='input-ghost' style='visibility:hidden; height:0'>");
                        element.attr("name",$(this).attr("name"));
                        element.change(function(){
                            element.next(element).find('input').val((element.val()).split('\\').pop());
                        });
                        $(this).find("button.btn-choose").click(function(){
                            element.click();
                        });
                        $(this).find("button.btn-reset").click(function(){
                            element.val(null);
                            $(this).parents(".input-file").find('input').val('');
                        });
                        $(this).find('input').css("cursor","pointer");
                        $(this).find('input').mousedown(function() {
                            $(this).parents('.input-file').prev().click();
                            return false;
                        });
                        return element;
                    }
                }
            );
        }
    </script>
@endsection

resources/views/posts/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Posts')

@section('content_header')
    <h1>Edit Post <a href="{{ route('posts.create') }}" class="btn btn-primary pull-right">Create</a></h1>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form class="form-horizontal" action="{{ route('posts.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="image">Post Banner</label>
                        <div class="input-group input-file" name="image">
                            <input type="text" class="form-control" placeholder='Choose a file...' />
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-choose" type="button">Choose</button>
                            </span>
                            <small id="titleHelp" class="form-text text-muted">{{ $errors->first('image') ?? 'This field required.' }}</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="image">Current Image</label>
                        <div class="clear"></div>
                        <img src="{{ asset('storage/' . $post->image) }}" class="col-lg-2 thumbnail img-responsive" />
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTitle">Post title</label>
                        <input type="text" name="title" class="form-control" value="{{ $post->title }}" id="exampleInputTitle" aria-describedby="titleHelp" placeholder="Enter title">
                        <small id="titleHelp" class="form-text text-muted">{{ $errors->first('title') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputSlug">Post slug</label>
                        <input type="text" name="slug" class="form-control" value="{{ $post->slug }}" id="exampleInputSlug" aria-describedby="slugHelp">
                        <small id="slugHelp" class="form-text text-muted">{{ $errors->first('slug') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="categories[]">Category</label>

                        <select name="categories[]" multiple data-live-search="true" class="form-control selectpicker">
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}" @if(in_array($category->id, $post->categories()->select('categories.id')->pluck('categories.id')->toArray())) selected @endif>{{ $category->title }}</option>
                            @endforeach
                        </select>
                        <small id="category_idHelp" class="form-text text-muted">{{ $errors->first('category_id') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDescription">Post short description</label>
                        <textarea name="description" class="form-control" id="exampleInputDescription" aria-describedby="descriptionHelp">{{ $post->description }}</textarea>
                        <small id="descriptionHelp" class="form-text text-muted">{{ $errors->first('description') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputBody">Post Content</label>
                        <textarea name="body" class="form-control" id="body" aria-describedby="bodyHelp">{{ $post->body }}</textarea>
                        <small id="bodyHelp" class="form-text text-muted">{{ $errors->first('body') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDescription">Post meta description</label>
                        <textarea name="meta_description" class="form-control" id="exampleInputDescription" aria-describedby="descriptionHelp">{{ $post->meta_description }}</textarea>
                        <small id="descriptionHelp" class="form-text text-muted">{{ $errors->first('meta_description') }}</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDescription">Post meta keywords</label>
                        <textarea name="meta_keywords" class="form-control" id="exampleInputDescription" aria-describedby="descriptionHelp">{{ $post->meta_keywords }}</textarea>
                        <small id="descriptionHelp" class="form-text text-muted">{{ $errors->first('meta_keywords') }}</small>
                    </div>
                    <div class="form-group">
                        <div class="form-check form-check-inline">
                            <label class="form-check-label col-md-2" for="is_active">
                                <input class="form-check-input" name="is_active" type="checkbox" id="is_active" @if($post->is_active) checked @endif > is active
                            </label>
                            <label class="form-check-label col-md-2" for="is_featured">
                                <input class="form-check-input" name="is_featured" type="checkbox" id="is_featured" @if($post->is_featured) checked @endif> is Published
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success pull-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
@endsection

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'body' );
    </script>
    <script>
        $(function() {
            bs_input_file();
        });

        function bs_input_file() {
            $(".input-file").before(
                function() {
                    if ( ! $(this).prev().hasClass('input-ghost') ) {
                        var element = $("<input type='file' class='input-ghost' style='visibility:hidden; height:0'>");
                        element.attr("name",$(this).attr("name"));
                        element.change(function(){
                            element.next(element).find('input').val((element.val()).split('\\').pop());
                        });
                        $(this).find("button.btn-choose").click(function(){
                            element.click();
                        });
                        $(this).find("button.btn-reset").click(function(){
                            element.val(null);
                            $(this).parents(".input-file").find('input').val('');
                        });
                        $(this).find('input').css("cursor","pointer");
                        $(this).find('input').mousedown(function() {
                            $(this).parents('.input-file').prev().click();
                            return false;
                        });
                        return element;
                    }
                }
            );
        }
    </script>
@endsection

resources/views/posts/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Posts')

@section('content_header')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <h1>List Posts <a href="{{ route('posts.create') }}" class="btn btn-primary pull-right">Create</a></h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="alert" id="alert"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered" id="posts-table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>thump</th>
                        <th>title</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                    </tr>
                </thead>
                <tbody>
                    @if($posts->count() > 0)
                        @foreach($posts as $key => $row)
                            <tr id="row_{{ $row->id }}">
                                <td>{{ ++$key }}</td>
                                <td class="col-md-2"><img src="{{ asset('storage/' . $row->image) }}" class="img-responsive" /> </td>
                                <td>{{ $row->title }}</td>
                                <td>{{ $row->created_at->format("F jS, Y") }}</td>
                                <td>
                                    <a href="javascript:deleteModelItem('Post', '{{$row->id}}');" class="btn btn-danger mr-3"><i class="fa fa-trash"></i> </a>
                                    <a href="{{ route('posts.edit', $row->id) }}" class="btn btn-warning"><i class="fa fa-edit"></i> </a>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="5">
                                There are no records.
                            </td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('css')
    <style>
        .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
            vertical-align: middle;
        }
    </style>
@endsection

@section('js')
    <script>

        function deleteModelItem(model, id) {
            if (confirm('Delete this Record?')) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    data: {id: id, model: model},
                    url: "{{ route('delete-record') }}",
                    type: "POST",
                    success: function (data) {
                        $('#alert').addClass('alert-success').html(data.message);
                        $('#row_' + id).hide();
                    },
                    error: function (data) {
                        console.log(data);
                        $('#alert').addClass('alert-danger').html(data.responseJSON.message);
                    }
                });
            }
        }
    </script>
@endsection

resources/views/posts/trash.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Trashed Posts')

@section('content_header')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <h1>Trashed Posts <a href="javascript:emptyModelTrash('Post')" class="btn btn-danger pull-right">Empty Trash</a></h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="alert" id="alert"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered" id="posts-table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>thump</th>
                    <th>title</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                </tr>
                </thead>
                <tbody>
                @if($posts->count() > 0)
                    @foreach($posts as $key => $row)
                        <tr id="row_{{ $row->id }}">
                            <td>{{ ++$key }}</td>
                            <td class="col-md-2"><img src="{{ asset('storage/' . $row->image) }}" class="img-responsive" /> </td>
                            <td>{{ $row->title }}</td>
                            <td>{{ $row->created_at->format("F jS, Y") }}</td>
                            <td>
                                <a href="javascript:restoreModelItem('Post', '{{$row->id}}');" class="btn btn-success mr-3"><i class="fa fa-reply"></i> </a>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="5">
                            There are no records.
                        </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('css')
    <style>
        .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
            vertical-align: middle;
        }
    </style>
@endsection

@section('js')
    <script>
        function prepareAjaxHeader() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        }

        function restoreModelItem(model, id) {
            prepareAjaxHeader();
            $.ajax({
                data: {id: id, model: model},
                url: "{{ route('restore-record') }}",
                type: "POST",
                success: function (data) {
                    $('#alert').addClass('alert-success').html(data.message);
                    $('#row_'+id).hide();
                },
                error: function(data) {
                    console.log(data);
                    $('#alert').addClass('alert-danger').html(data.responseJSON.message);
                }
            });
        }

        function emptyModelTrash(model) {
            prepareAjaxHeader();
            $.ajax({
                data: {model: model},
                url: "{{ route('empty-records') }}",
                type: "POST",
                success: function (data) {
                    $('#alert').addClass('alert-success').html(data.message);
                    $('.posts-table tbody tr').slideUp();
                },
                error: function(data) {
                    console.log(data);
                    $('#alert').addClass('alert-danger').html(data.responseJSON.message);
                }
            });
        }
    </script>
@endsection

resources/views/posts/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/24/2018
 * Time: 10:56 PM
 */
?>
@extends('app')
@section('content')
<!-- Page Content -->
<div class="container mt-5">

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-9">
            <!-- Title -->
            <h1 class="mt-4">{{ $post->title }}</h1>
            <hr>
            <!-- Date/Time -->
            <p>Posted on {{ $post->created_at->format("F jS, Y") }} at {{ $post->created_at->format("H:i a") }}</p>

            <hr>

            <!-- Preview Image -->
            <img class="img-fluid rounded" src="{{ asset('storage/' . $post->image) }}" alt="{{ $post->title }}">

            <hr>

            <!-- Post Content -->
            {!! $post->body !!}

        </div>

        <!-- Sidebar Widgets Column -->


        <!-- Sidebar Widgets Column -->
        <div class="col-md-3">

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <ul class="list-unstyled mb-0">
                        @foreach($categories as $cat)
                            <li>
                                <a href="{{ route('category-view', $cat->id) }}">{{ $cat->title }}</a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->

</div>
<!-- /.container -->
@endsection