routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/post/{slug}', 'HomeController@post_view')->name('post-view');
Route::get('/category/{id}', 'HomeController@category_view')->name('category-view');
Route::get('/admin', 'DashboardController@dashboard')->name('home');
Route::post('delete-record',array('as' => "delete-record",'uses'=> "DashboardController@delete_record"));
Route::post('restore-record',array('as' => "restore-record",'uses'=> "DashboardController@restore_record"));
Route::post('empty-records',array('as' => "empty-records",'uses'=> "DashboardController@empty_records"));
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::get('/categories/trash', 'CategoryController@trash');
    Route::resource('categories', 'CategoryController');
    Route::get('/posts/trash', 'PostController@trash');
    Route::resource('posts', 'PostController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Category extends Model
{
    use SoftDeletes;
    protected $fillable = ['title', 'image'];
    protected $dates = ['deleted_at'];
    public static $rules = [
        'title' => 'required',
        'image' => 'required|image|dimensions:width=1920,height=1280'
    ];
    public static $update_rules = [
        'title' => 'required',
        'image' => 'nullable|image|dimensions:width=1920,height=1280'
    ];

    public function posts() {
        return $this->belongsToMany(Post::class);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('categories.index')->with(['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, Category::$rules);
        $image = $request->image->store('images/categories');
        Category::create(['title' => $request->title, 'image' => $image]);
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.edit')->with(['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Category $category
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Category $category)
    {
        $this->validate($request, Category::$update_rules);
        $title = $request->title ?? $category->title;
        $image = $request->image->store('images/categories') ?? $category->image;
        $category->update(['title' => $title, 'image' => $image]);
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category $category
     * @return void
     */
    public function destroy(Category $category)
    {
        //
    }

    public function trash() {
        //
        $categories = Category::onlyTrashed()->get();
        return view('categories.trash', ['categories' => $categories]);
    }

    public function emptyTrash() {
        Category::onlyTrashed()->forceDelete();
        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Categories')

@section('content_header')
    <h1>List Categories <a href="{{ route('categories.create') }}" class="btn btn-primary pull-right">Create</a></h1>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form class="form-horizontal" action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputTitle">Category title</label>
                        <input type="text" name="title" class="form-control" id="exampleInputTitle" aria-describedby="titleHelp" placeholder="Enter title">
                        <small id="titleHelp" class="form-text text-muted">{{ $errors->first('title') ?? 'This field must be unquie.' }}</small>
                    </div>
                    <div class="form-group">
                        <label for="image">Current Image</label>
                        <div class="input-group input-file" name="image">
                            <input type="text" class="form-control" placeholder='Choose a file...' />
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-choose" type="button">Choose</button>
                            </span>
                            <small id="titleHelp" class="form-text text-muted">{{ $errors->first('image') ?? 'This field required.' }}</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success pull-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('css')
@endsection

@section('js')
    <script>
        $(function() {
            bs_input_file();
        });

        function bs_input_file() {
            $(".input-file").before(
                function() {
                    if ( ! $(this).prev().hasClass('input-ghost') ) {
                        var element = $("<input type='file' class='input-ghost' style='visibility:hidden; height:0'>");
                        element.attr("name",$(this).attr("name"));
                        element.change(function(){
                            element.next(element).find('input').val((element.val()).split('\\').pop());
                        });
                        $(this).find("button.btn-choose").click(function(){
                            element.click();
                        });
                        $(this).find("button.btn-reset").click(function(){
                            element.val(null);
                            $(this).parents(".input-file").find('input').val('');
                        });
                        $(this).find('input').css("cursor","pointer");
                        $(this).find('input').mousedown(function() {
                            $(this).parents('.input-file').prev().click();
                            return false;
                        });
                        return element;
                    }
                }
            );
        }
    </script>
@endsection

resources/views/categories/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Categories')

@section('content_header')
    <h1>List Categories <a href="{{ route('categories.create') }}" class="btn btn-primary pull-right">Create</a></h1>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form class="form-horizontal" action="{{ route('categories.update', $category) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="exampleInputTitle">Category title</label>
                        <input type="text" name="title" class="form-control" value="{{ $category->title }}" id="exampleInputTitle" aria-describedby="titleHelp" placeholder="Enter title">
                        <small id="titleHelp" class="form-text text-muted">{{ $errors->first('title') ?? 'This field must be unquie.' }}</small>
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <div class="input-group input-file" name="image">
                            <input type="text" class="form-control" placeholder='Choose a file...' />
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-choose" type="button">Choose</button>
                            </span>
                            <small id="titleHelp" class="form-text text-muted">{{ $errors->first('image') ?? 'This field required.' }}</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="image">Current Image</label>
                        <div class="clear"></div>
                        <img src="{{ asset('storage/' . $category->image) }}" class="col-lg-2 thumbnail img-responsive" />
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success pull-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('css')
@endsection

@section('js')
    <script>
        $(function() {
            bs_input_file();
        });

        function bs_input_file() {
            $(".input-file").before(
                function() {
                    if ( ! $(this).prev().hasClass('input-ghost') ) {
                        var element = $("<input type='file' class='input-ghost' style='visibility:hidden; height:0'>");
                        element.attr("name",$(this).attr("name"));
                        element.change(function(){
                            element.next(element).find('input').val((element.val()).split('\\').pop());
                        });
                        $(this).find("button.btn-choose").click(function(){
                            element.click();
                        });
                        $(this).find("button.btn-reset").click(function(){
                            element.val(null);
                            $(this).parents(".input-file").find('input').val('');
                        });
                        $(this).find('input').css("cursor","pointer");
                        $(this).find('input').mousedown(function() {
                            $(this).parents('.input-file').prev().click();
                            return false;
                        });
                        return element;
                    }
                }
            );
        }
    </script>
@endsection

resources/views/categories/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Categories')

@section('content_header')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <h1>List Categories <a href="{{ route('categories.create') }}" class="btn btn-primary pull-right">Create</a></h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="alert" id="alert"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered" id="categories-table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>thump</th>
                        <th>title</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                    </tr>
                </thead>
                <tbody>
                    @if($categories->count() > 0)
                        @foreach($categories as $key => $row)
                            <tr id="row_{{ $row->id }}">
                                <td>{{ ++$key }}</td>
                                <td class="col-md-2"><img src="{{ asset('storage/' . $row->image) }}" class="img-responsive" /> </td>
                                <td>{{ $row->title }}</td>
                                <td>{{ $row->created_at->format("F jS, Y") }}</td>
                                <td>
                                    <a href="javascript:deleteModelItem('Category', '{{$row->id}}');" class="btn btn-danger mr-3"><i class="fa fa-trash"></i> </a>
                                    <a href="{{ route('categories.edit', $row->id) }}" class="btn btn-warning"><i class="fa fa-edit"></i> </a>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="5">
                                There are no records.
                            </td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('css')
    <style>
        .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
            vertical-align: middle;
        }
    </style>
@endsection

@section('js')
    <script>

        function deleteModelItem(model, id) {
            if (confirm('Delete this Record?')) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    data: {id: id, model: model},
                    url: "{{ route('delete-record') }}",
                    type: "POST",
                    success: function (data) {
                        $('#alert').addClass('alert-success').html(data.message);
                        $('#row_' + id).hide();
                    },
                    error: function (data) {
                        console.log(data);
                        $('#alert').addClass('alert-danger').html(data.responseJSON.message);
                    }
                });
            }
        }
    </script>
@endsection

resources/views/categories/trash.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/23/2018
 * Time: 6:08 PM
 */
?>

@extends('adminlte::page')

@section('title', 'Trashed Categories')

@section('content_header')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <h1>Trashed Categories <a href="javascript:emptyModelTrash('Category')" class="btn btn-danger pull-right">Empty Trash</a></h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="alert" id="alert"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered" id="categories-table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>thump</th>
                    <th>title</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                </tr>
                </thead>
                <tbody>
                @if($categories->count() > 0)
                    @foreach($categories as $key => $row)
                        <tr id="row_{{ $row->id }}">
                            <td>{{ ++$key }}</td>
                            <td class="col-md-2"><img src="{{ asset('storage/' . $row->image) }}" class="img-responsive" /> </td>
                            <td>{{ $row->title }}</td>
                            <td>{{ $row->created_at->format("F jS, Y") }}</td>
                            <td>
                                <a href="javascript:restoreModelItem('Category', '{{$row->id}}');" class="btn btn-success mr-3"><i class="fa fa-reply"></i> </a>
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="5">
                            There are no records.
                        </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('css')
    <style>
        .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
            vertical-align: middle;
        }
    </style>
@endsection

@section('js')
    <script>
        function prepareAjaxHeader() {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
        }

        function restoreModelItem(model, id) {
            prepareAjaxHeader();
            $.ajax({
                data: {id: id, model: model},
                url: "{{ route('restore-record') }}",
                type: "POST",
                success: function (data) {
                    $('#alert').addClass('alert-success').html(data.message);
                    $('#row_'+id).hide();
                },
                error: function(data) {
                    console.log(data);
                    $('#alert').addClass('alert-danger').html(data.responseJSON.message);
                }
            });
        }

        function emptyModelTrash(model) {
            prepareAjaxHeader();
            $.ajax({
                data: {model: model},
                url: "{{ route('empty-records') }}",
                type: "POST",
                success: function (data) {
                    $('#alert').addClass('alert-success').html(data.message);
                    $('#row_'+id).hide();
                },
                error: function(data) {
                    console.log(data);
                    $('#alert').addClass('alert-danger').html(data.responseJSON.message);
                }
            });
        }
    </script>
@endsection

resources/views/categories/view.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Alaa M. Jaddou
 * Date: 10/24/2018
 * Time: 10:39 PM
 */
?>
@extends('app')

@section('content')
<!-- Page Content -->
<div class="container mt-5">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="my-4">
                {{ $category->title }}
            </h1>

            <!-- Blog Post -->
            @foreach($category->posts as $post)
                <div class="card mb-4">
                    <img class="card-img-top" src="{{ asset('storage/'.$post->image) }}" alt="{{ $post->title }}">
                    <div class="card-body">
                        <h2 class="card-title">{{ $post->title }}</h2>
                        <p class="card-text">{{ $post->description }}</p>
                        <a href="{{ route('post-view', $post->slug) }}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                    <div class="card-footer text-muted">
                        Posted on {{ $post->created_at->format("F jS, Y") }}
                    </div>
                </div>
            @endforeach

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Categories Widget -->
            <div class="card my-4">
                <h5 class="card-header">Categories</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled mb-0">
                                @foreach($categories as $cat)
                                    <li>
                                        <a href="{{ route('category-view', $cat->id) }}">{{ $cat->title }}</a>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->
@endsection